package:
  name: eigen3
  version: "3.3.9"

source:
  fn: eigen3-3.3.9.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
  sha256: 7985975b787340124786f092b3a07d594b2e9cd53bbfe5f3d9b1daee7d55f56f

requirements:
  build:
    - cmake
    - {{compiler("cxx")}}
    
test:
  files:
    - test.cc

build:
  number: 2

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
