FROM quay.io/pypa/musllinux_1_2_x86_64

RUN apk add wget eigen-dev openblas-dev hdf5-dev

COPY install_dependencies.sh /tmp/install_dependencies.sh
RUN chmod +x /tmp/install_dependencies.sh && /tmp/install_dependencies.sh && rm /tmp/install_dependencies.sh
