FROM quay.io/pypa/manylinux_2_28_x86_64

RUN yum -y install wget openblas-devel hdf5-devel && \
   yum clean all

COPY install_dependencies.sh /tmp/install_dependencies.sh
RUN chmod +x /tmp/install_dependencies.sh && /tmp/install_dependencies.sh && rm /tmp/install_dependencies.sh
