FROM quay.io/pypa/musllinux_1_2_x86_64

RUN apk add wget eigen-dev openblas-dev hdf5-dev

#install HighFive
RUN wget -O HighFive.tar.gz https://github.com/BlueBrain/HighFive/archive/v2.2.2.tar.gz && \
    tar xzf HighFive.tar.gz && \
    rm HighFive.tar.gz && \
    cd HighFive* && \
    mkdir build && \
    cd build && \
    cmake .. -DHIGHFIVE_USE_BOOST=OFF && \
    make -j2 && \
    make install && \
    cd ../.. && \
    rm -r HighFive*
